
---
spring:
  config.activate.on-profile: default
cds:
  datasource.auto-config.enabled: true
---
spring:
  config:
    activate:
      on-profile: cloud
cds:
  multi-tenancy:
    mtxs:
      enabled: true
---
spring:
  config.activate.on-profile: hybrid
cds:
  multi-tenancy:
    mtxs.enabled: true
    sidecar.url: http://localhost:4005/ # in production mode overwrite with the URL from mta.yaml
